remeshing triggered by minimum mesh quality #1961
feelpp/feelpp pull request #1966
Opened 2022-10-04 09:57 UTC by lberti

- [ x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/feelpp/feelpp/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes?
- [ ] Have you successfully run the Feel++ testsuite with your changes locally?
- [ ] Have you written Doxygen comments in your contribution ?

-----

2022-10-06 20:51 UTC, prudhomm approved these changes
@lberti it seems ok to me but there are a few update to do I think

2022-10-06 20:51 UTC, prudhomm commented on toolboxes/feel/feelmodels/modelcore/modelmeshes.hpp
> +            double M_min_quality_mas=0.9;
@lberti what does `mas` mean? shouldn't it be threshold ?

2022-10-06 20:51 UTC, prudhomm commented on toolboxes/feel/feelmodels/modelmesh/meshale.hpp
> +    void attachModelMeshesptr(std::shared_ptr<ModelMesh<index_type>> const& modelMesh_ptr);
rename to `attachModelMeshes` ?

2022-10-06 20:51 UTC, prudhomm commented on toolboxes/fluid/cases/TurekHron/moving_body/cfd3.json
> +                            // "min_quality":0.4
why is it commented out ? would it be possible to add a test for this ?

2022-10-07 06:43 UTC, vincentchabannes requested changes
@lberti this is a first step but still a lot of thing to handle.
 We probably need to change the weak ptr with a raw ptr in order to avoid the shared_from_this inheritance. The observer desgin pattern should be improved, and the event mesh_quality should be handle when the mesh is moved (and even before), not in the event each_time_step. Also, I think here the mesh quality is evaluated at each time, it shouldn't , only when the json say that this event can appear. The json section should be also improved.

2022-10-07 08:07 UTC, prudhomm commented
@vincentchabannes what do you mean by should be improved? what is wrong with the current implementation of the observer pattern ? may be I should have a look more closely and not just the diff.
regarding the computational efficiency I agree.

2022-12-22 23:25 UTC, closed without merging