2272 fix nirb
feelpp/feelpp pull request #2287
Opened 2024-10-03 15:12 UTC by thomas-saigre

- fixes #2272

Some bugs were still present in the NIRB code, this PR corrected them (at least some of them).

2024-10-05 20:09 UTC, prudhomm approved these changes

2024-10-05 20:12 UTC, prudhomm commented
@thomas-saigre the toolboxes are failed in thermal bridge it seems. Any idea ?  perhaps restart just the toolboxs would be fine ?

2024-10-06 08:31 UTC, thomas-saigre commented
@prudhomm No, I don't see why it has failed, except some configuration files, I have not made any change in the `toolbox` directory. I'll try to re-run the CI

2024-10-06 08:34 UTC, thomas-saigre commented
After looking more in details, it may have failed because I changed the discretization `P1` to `P2` in the cfg file of the testcase `ThermalBridgesENISO10211`, I will revert it to see
``` #6 16970.7 The following tests FAILED:
#6 16970.7 	101 - feelpp_toolbox_heat-ThermalBridgesENISO10211_case2_testsuite-np-6 (Failed)
#6 16970.7 	102 - feelpp_toolbox_heat-ThermalBridgesENISO10211_case2_testsuite-np-1 (Failed)```

2024-10-06 08:37 UTC, prudhomm commented
you should discuss this with @vincentchabannes ASAP, the testcase will need to be updated in a near future to accomodate the new version of the thermal bridge documentation. 
Did you try the 3D version of thermal bridge or only the 2D one ?

2024-10-06 08:38 UTC, prudhomm commented
this definitely needs investigation. Perhaps a mesh convergence analysis would be very useful for different polynomial orders

2024-10-07 16:18 UTC, thomas-saigre commented
@prudhomm this time it seems that the CI job was killed even before the compilation was completed:
```cpp
#7 14067.3 [ 87%] Built target feelpp_toolbox_fluid_lib_2dP2P1G2
#7 14067.3 [ 87%] Building CXX object toolboxes/feel/feelmodels/fsi/CMakeFiles/feelpp_toolbox_fsi_lib_3dP1P1G1_3dP1G1.dir/3dP1P1G1_3dP1G1/fsi_inst.cpp.o
#7 14073.3 [ 87%] Building CXX object toolboxes/feel/feelmodels/heatfluid/CMakeFiles/feelpp_toolbox_heatfluid_lib_2dP1G1_2dP3P2G1.dir/2dP1G1_2dP3P2G1/heatfluidassemblylinear_inst.cpp.o
#7 14117.3 [ 87%] Building CXX object toolboxes/feel/feelmodels/fsi/CMakeFiles/feelpp_toolbox_fsi_lib_3dP1P1G1_3dP1G1.dir/3dP1P1G1_3dP1G1/fsibc_inst.cpp.o
#7 14117.3 [ 87%] Building CXX object toolboxes/feel/feelmodels/fsi/CMakeFiles/feelpp_toolbox_fsi_lib_3dP1P1G1_3dP1G1.dir/3dP1P1G1_3dP1G1/fsibc_inst.cpp.o
feelpp/tools/scripts/buildkite/install-feelpp.sh: line 73: 597041 Killed                  docker build --pull --tag=ghcr.io/feelpp/${image}:${tag} --build-arg=BUILD_JOBS=${JOBS} --build-arg=BRANCH=${BRANCH} --build-arg=CXX="${CXX}" --build-arg=CC="${CC}" --build-arg=CONFIGURE_FLAGS="${CONFIGURE_FLAGS}" --build-arg=CMAKE_FLAGS="${CMAKE_FLAGS}" --build-arg=CTEST_FLAGS="${CTEST_FLAGS}" --no-cache=true -f docker/${image}/dockerfile.tmp docker/${image}
Error: Process completed with exit code 137.```

2025-02-20 13:08 UTC, thomas-saigre commented
@prudhomm the CI failed, it seems that the process was killed, but I cannot tell why...

```
 /data/cemosis/github-actions-runner/actions-runner-2/_work/_temp/71d9f49f-0e7a-45a2-a33b-e5c62d8f9040.sh: line 2: 1211022 Killed                  feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp
Error: Process completed with exit code 137.
```

2025-02-20 15:46 UTC, prudhomm commented
> @prudhomm the CI failed, it seems that the process was killed, but I cannot tell why...
> 
> ```
>  /data/cemosis/github-actions-runner/actions-runner-2/_work/_temp/71d9f49f-0e7a-45a2-a33b-e5c62d8f9040.sh: line 2: 1211022 Killed                  feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp
> Error: Process completed with exit code 137.
> ```

probably someone kiiled it

2025-02-21 08:26 UTC, prudhomm requested changes

2025-02-21 08:26 UTC, prudhomm commented on toolboxes/heat/cases/Building/ThermalBridgesENISO10211/case2.json
@thomas-saigre @vincentchabannes it seems that these changes broke the test case here  systematically
https://github.com/feelpp/feelpp/actions/runs/13435775386/job/37551254675#step:3:5139

2025-02-21 08:31 UTC, thomas-saigre commented on toolboxes/heat/cases/Building/ThermalBridgesENISO10211/case2.json
yes indeed, I'm looking at it

2025-02-21 11:52 UTC, thomas-saigre commented on toolboxes/heat/cases/Building/ThermalBridgesENISO10211/case2.json
I thought it was only an issue of config file, but no : taking the previous version and running the test at the current state of the code still results in erroneous values...
I'm making a `git bisect` to find where it would have failed... From the list of modified files in the PR, I cannot tell what change makes this fail :/

2025-02-21 15:56 UTC, thomas-saigre commented on toolboxes/heat/cases/Building/ThermalBridgesENISO10211/case2.json
seems that the error was due to
```diff
- filename=$cfgdir/case2.json
+ json.filename=$cfgdir/case2.json
```
in the config file...

I couldn't tell why it did break the test... But now it is corrected, the pipeline should proceed correctly :crossed_fingers:

2025-02-22 06:29 UTC, prudhomm commented
@thomas-saigre now it breaks later  in the python part https://github.com/feelpp/feelpp/actions/runs/13460439204/job/37634551569#step:3:2691

it seems that you changed or renamed a parameter in the lib but not in the tests

2025-02-23 00:02 UTC, merged